version: '3.8'

services:
  # 1. KAFKA (Le Centre de Tri)
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  # 2. API ÉCRITURE (Post) -> Port 8000
  api_write:
    build: .
    container_name: api_writer
    #Docker lance producer.py
    command: ["uvicorn", "producer:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    volumes:
      - ./:/app

  # 3. API LECTURE (Lecteur) -> Port 8001
  api_read:
    build: .
    container_name: api_reader
    # On force Docker à lancer reader.py
    command: ["uvicorn", "reader:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    volumes:
      # CRITIQUE : Il doit avoir accès au fichier DB créé par le consumer
      - ./:/app

  # 4. CONSUMER (L'Ouvrier) -> Arrière-plan
  consumer:
    build: .
    container_name: consumer_worker
    # On force Docker à lancer consumer.py
    command: ["python", "consumer.py"]
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    volumes:
      # CRITIQUE : C'est lui qui écrit dans le fichier DB
      - ./:/app